[package]
name = "route-parser-macos"
version = "0.1.0"
edition = "2021"

[dependencies]
cidr = { version = "0.2", features = ["serde"] }
mac_address = "1"
tokio = { version = "1", features = ["full"] }