[package]
name = "route-parser-macos"
version = "0.1.0"
edition = "2021"

[dependencies]
cidr = { version = "0.2", features = ["serde"] }
mac_address = "1"
thiserror = "1"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
anyhow = "1"

[lints.clippy]
all = "warn"
pedantic = "warn"